name: "Setup Python via pixi"
description: "setup Python and pixi with caches"
inputs:
  cache-esgf:
    description: "Cache any downloaded ESGF data"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: "latest"
        cache: true
    - name: Install the project
      shell: bash
      run: |
        # Only installs if the lock file is up-to-date with the manifest
        pixi install --locked
    - name: Cache downloaded ESGF data
      uses: actions/cache@v4
      if: ${{ inputs.cache-esgf == 'true' }}
      with:
        path: |
          ~/.esgf
        key: esgf
