name: "Setup Python and uv"
description: "setup Python and uv with caches"
inputs:
  python-version:
    description: "The version of Python to use"
    required: true
    default: "3.11"
  uv-version:
    description: "The version of uv to use"
    required: true
    default: ">=0.4.20"
  cache-esgf:
    description: "Cache any downloaded ESGF data"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true
    # Install a specific version of python
    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}
    # Install dependencies and builds the rust crate
    - name: Install the project
      shell: bash
      run: |
        uv sync --all-extras --dev --locked
    - name: Cache downloaded ESGF data
      uses: actions/cache@v4
      if: ${{ inputs.cache-esgf == 'true' }}
      with:
        path: |
          ~/.esgf
        key: esgf
