name: "Regenerate sample data"
description: "Runs the regenerate sample data workflow and commits the result"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup
      with:
        python-version: 3.12

    - name: Verify registry
      shell: bash
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$CI_COMMIT_EMAIL"

        make fetch-test-data
        make registry.txt
        git diff

        git add data registry.txt
        git commit -m "Updated sample data"
        git push
